<?php

use App\Http\Controllers\Api\AppVersionController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ExerciseController;
use App\Http\Controllers\Api\CoachManagementController;
use App\Http\Controllers\Api\GoalController;
use App\Http\Controllers\Api\TodoTaskController;
use App\Http\Controllers\Api\CommentController;
use App\Http\Controllers\Api\CommentReactionController;
use App\Http\Controllers\Api\CalorieController;
use App\Http\Controllers\Api\FastingController;
use App\Http\Controllers\Api\DailyTrackerController;
use App\Http\Controllers\Api\DailyCheckInController;
use App\Http\Controllers\Api\ChatController;
use App\Http\Controllers\Api\WalkController;
use App\Http\Controllers\Api\UserPointController;
use App\Http\Controllers\Api\EmotionController;
use App\Http\Controllers\Api\CommunityController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\AdminUserController;
use App\Http\Controllers\Api\AbundanceAdminController;
use App\Http\Controllers\Api\CompanyController;
use App\Http\Controllers\Api\LeaderboardController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\PostHeartController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\StepSubmissionController;
use App\Http\Controllers\Api\AccountabilityMeetingController;
use App\Http\Controllers\Api\AnalyticsEmployeeScoreController;
use App\Http\Controllers\Api\AbundanceA12SessionController;
use App\Http\Controllers\Api\AbundanceCouncilFallbackController;
use Illuminate\Support\Facades\Route;

Route::get('/health', fn () => response()->json([
    'ok' => true,
    'service' => config('app.name'),
    'timestamp' => now()->toIso8601String(),
]));

Route::get('/app-version', [AppVersionController::class, 'show']);

Route::prefix('auth')->group(function (): void {
    Route::post('/register', [AuthController::class, 'register']);
    Route::post('/company-code/validate', [AuthController::class, 'validateCompanyCode']);
    Route::post('/login', [AuthController::class, 'login']);
    Route::post('/google', [AuthController::class, 'google']);
    Route::post('/apple', [AuthController::class, 'apple']);
    Route::post('/email/verification-notification', [AuthController::class, 'resendVerificationEmail']);
    Route::post('/password/forgot', [AuthController::class, 'sendPasswordResetLink']);
    Route::post('/password/reset', [AuthController::class, 'resetPassword']);
});

Route::middleware('auth:sanctum')->group(function (): void {
    Route::post('/abundance/a12/session', AbundanceA12SessionController::class);
    Route::get('/abundance/councils', [AbundanceCouncilFallbackController::class, 'councils']);
    Route::get('/abundance/guild', [AbundanceCouncilFallbackController::class, 'guild']);
    Route::post('/abundance/guild/join', [AbundanceCouncilFallbackController::class, 'join']);
    Route::post('/abundance/guild/leave', [AbundanceCouncilFallbackController::class, 'leave']);
    Route::get('/me', [ProfileController::class, 'show']);
    Route::patch('/me', [ProfileController::class, 'update']);
    Route::delete('/me', [AuthController::class, 'destroy']);
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::post('/media/upload', [ProfileController::class, 'uploadMedia']);
    Route::get('/dashboard', [DashboardController::class, 'show']);
    Route::get('/admin/users', [AdminUserController::class, 'index']);
    Route::patch('/admin/users/{user}/role', [AdminUserController::class, 'updateRole']);
    Route::get('/admin/abundance', [AbundanceAdminController::class, 'index']);
    Route::post('/admin/abundance/assignments', [AbundanceAdminController::class, 'assign']);
    Route::delete('/admin/abundance/assignments/{studentId}', [AbundanceAdminController::class, 'remove']);
    Route::patch('/admin/abundance/goals/{goalId}', [AbundanceAdminController::class, 'updateGoal']);
    Route::post('/admin/abundance/goals/{goalId}/tasks', [AbundanceAdminController::class, 'storeTask']);
    Route::get('/admin/analytics/employee-scores', [AnalyticsEmployeeScoreController::class, 'index']);
    Route::get('/companies', [CompanyController::class, 'index']);
    Route::get('/companies/lookup', [CompanyController::class, 'lookup']);
    Route::post('/companies', [CompanyController::class, 'store']);
    Route::patch('/companies/{company}', [CompanyController::class, 'update']);
    Route::get('/companies/{company}/members', [CompanyController::class, 'members']);
    Route::delete('/companies/{company}', [CompanyController::class, 'destroy']);
    Route::get('/community/posts', [CommunityController::class, 'index']);
    Route::get('/community/mentionable-users', [CommunityController::class, 'mentionableUsers']);
    Route::post('/community/posts', [CommunityController::class, 'store']);
    Route::get('/community/posts/{post}', [CommunityController::class, 'show']);
    Route::patch('/community/posts/{post}', [CommunityController::class, 'update']);
    Route::delete('/community/posts/{post}', [CommunityController::class, 'destroy']);
    Route::get('/community/posts/{post}/hearts', [CommunityController::class, 'hearts']);
    Route::get('/community/posts/{post}/comments', [CommentController::class, 'index']);
    Route::post('/community/posts/{post}/comments', [CommentController::class, 'store']);
    Route::patch('/community/posts/{post}/comments/{comment}', [CommentController::class, 'update']);
    Route::delete('/community/posts/{post}/comments/{comment}', [CommentController::class, 'destroy']);
    Route::post('/community/posts/{post}/comments/{comment}/reactions', [CommentReactionController::class, 'store']);
    Route::delete('/community/posts/{post}/comments/{comment}/reactions', [CommentReactionController::class, 'destroy']);
    Route::post('/community/posts/{post}/hearts', [PostHeartController::class, 'store']);
    Route::delete('/community/posts/{post}/hearts', [PostHeartController::class, 'destroy']);
    Route::get('/chat-rooms', [ChatController::class, 'index']);
    Route::post('/chat-rooms', [ChatController::class, 'storeRoom']);
    Route::get('/chat-rooms/{chatRoom}', [ChatController::class, 'show']);
    Route::get('/chat-rooms/{chatRoom}/messages', [ChatController::class, 'messages']);
    Route::post('/chat-rooms/{chatRoom}/messages', [ChatController::class, 'storeMessage']);
    Route::patch('/chat-rooms/{chatRoom}/read', [ChatController::class, 'markRead']);
    Route::get('/walk-invite-candidates', [WalkController::class, 'inviteCandidates']);
    Route::get('/walk-sessions', [WalkController::class, 'sessions']);
    Route::post('/walk-sessions', [WalkController::class, 'storeSession']);
    Route::get('/walk-sessions/{walkSession}/members', [WalkController::class, 'members']);
    Route::post('/walk-sessions/{walkSession}/members', [WalkController::class, 'storeMember']);
    Route::delete('/walk-sessions/{walkSession}/members/{userId}', [WalkController::class, 'destroyMember']);
    Route::get('/walk-invites', [WalkController::class, 'invites']);
    Route::post('/walk-invites', [WalkController::class, 'storeInvite']);
    Route::patch('/walk-invites/{walkInvite}', [WalkController::class, 'updateInvite']);
    Route::get('/recorded-walks', [WalkController::class, 'recorded']);
    Route::post('/recorded-walks', [WalkController::class, 'storeRecorded']);
    Route::delete('/recorded-walks/{recordedWalk}', [WalkController::class, 'destroyRecorded']);
    Route::get('/todo-tasks', [TodoTaskController::class, 'index']);
    Route::post('/todo-tasks', [TodoTaskController::class, 'store']);
    Route::patch('/todo-tasks/{todoTask}', [TodoTaskController::class, 'update']);
    Route::delete('/todo-tasks/{todoTask}', [TodoTaskController::class, 'destroy']);
    Route::get('/leaderboard', [LeaderboardController::class, 'index']);
    Route::get('/coaches', [CoachManagementController::class, 'directory']);
    Route::get('/emotions/today', [EmotionController::class, 'today']);
    Route::get('/emotions/history', [EmotionController::class, 'history']);
    Route::post('/emotions/today', [EmotionController::class, 'store']);
    Route::get('/daily-check-ins', [DailyCheckInController::class, 'show']);
    Route::get('/daily-check-ins/history', [DailyCheckInController::class, 'history']);
    Route::post('/daily-check-ins', [DailyCheckInController::class, 'upsert']);
    Route::get('/goals', [GoalController::class, 'index']);
    Route::post('/goals', [GoalController::class, 'store']);
    Route::get('/goals/{goal}', [GoalController::class, 'show']);
    Route::patch('/goals/{goal}', [GoalController::class, 'update']);
    Route::delete('/goals/{goal}', [GoalController::class, 'destroy']);
    Route::get('/goals/{goal}/tasks', [GoalController::class, 'tasks']);
    Route::post('/goals/{goal}/tasks', [GoalController::class, 'storeTask']);
    Route::patch('/goals/{goal}/tasks/{task}', [GoalController::class, 'updateTaskStatus']);
    Route::delete('/goals/{goal}/tasks/{task}', [GoalController::class, 'destroyTask']);
    Route::get('/goals/{goal}/updates', [GoalController::class, 'updates']);
    Route::get('/goals/{goal}/comments', [GoalController::class, 'comments']);
    Route::post('/goals/{goal}/comments', [GoalController::class, 'storeComment']);
    Route::get('/goals/{goal}/merits', [GoalController::class, 'merits']);
    Route::post('/goals/{goal}/measure', [GoalController::class, 'updateMeasure']);
    Route::post('/goals/{goal}/merits/target', [GoalController::class, 'logMeritTarget']);
    Route::post('/goals/{goal}/merits/extra', [GoalController::class, 'goExtraMile']);
    Route::get('/daily-tracker', [DailyTrackerController::class, 'show']);
    Route::get('/daily-tracker/history', [DailyTrackerController::class, 'history']);
    Route::get('/daily-tracker/friends', [DailyTrackerController::class, 'friends']);
    Route::post('/daily-tracker', [DailyTrackerController::class, 'upsert']);
    Route::get('/admin/daily-tracker', [DailyTrackerController::class, 'adminOverview']);
    Route::post('/user-points', [UserPointController::class, 'upsert']);
    Route::get('/calorie', [CalorieController::class, 'show']);
    Route::get('/calorie/history', [CalorieController::class, 'history']);
    Route::post('/calorie/day', [CalorieController::class, 'upsertDay']);
    Route::post('/calorie/entries', [CalorieController::class, 'storeEntry']);
    Route::get('/calorie/food-memory/{key}', [CalorieController::class, 'showFoodMemory']);
    Route::post('/calorie/food-memory', [CalorieController::class, 'upsertFoodMemory']);
    Route::get('/fasting', [FastingController::class, 'show']);
    Route::get('/fasting/history', [FastingController::class, 'history']);
    Route::post('/fasting/start', [FastingController::class, 'start']);
    Route::post('/fasting/end', [FastingController::class, 'end']);
    Route::get('/exercise/history', [ExerciseController::class, 'history']);
    Route::get('/exercise', [ExerciseController::class, 'index']);
    Route::post('/exercise', [ExerciseController::class, 'store']);
    Route::delete('/exercise/{logId}', [ExerciseController::class, 'destroy']);
    Route::get('/coach/groups', [CoachManagementController::class, 'groups']);
    Route::get('/coach/users', [CoachManagementController::class, 'users']);
    Route::post('/coach/groups', [CoachManagementController::class, 'storeGroup']);
    Route::patch('/coach/groups/{group}', [CoachManagementController::class, 'updateGroup']);
    Route::patch('/coach/groups/{group}/coaches', [CoachManagementController::class, 'updateGroupCoaches']);
    Route::post('/coach/groups/{group}/remove-mentee', [CoachManagementController::class, 'removeMenteeFromGroup']);
    Route::delete('/coach/groups/{group}', [CoachManagementController::class, 'destroyGroup']);
    Route::get('/coach/mentees', [CoachManagementController::class, 'mentees']);
    Route::get('/coach/my-coaches', [CoachManagementController::class, 'myCoaches']);
    Route::get('/coach/mentees/{menteeId}/latest-tracker', [CoachManagementController::class, 'latestTracker']);
    Route::get('/coach/mentees/{menteeId}/trackers', [CoachManagementController::class, 'trackers']);
    Route::get('/coach/mentees/{menteeId}/goals', [CoachManagementController::class, 'menteeGoals']);
    Route::get('/coach/goals', [GoalController::class, 'coachGoalsRoster']);
    Route::get('/coach/mentees/{menteeId}/todo-tasks', [CoachManagementController::class, 'menteeTodoTasks']);
    Route::post('/coach/mentees/assign', [CoachManagementController::class, 'assignMentee']);
    Route::delete('/coach/mentees/{menteeId}', [CoachManagementController::class, 'removeMentee']);
    Route::get('/coach/requests', [CoachManagementController::class, 'requests']);
    Route::get('/coach/my-applications', [CoachManagementController::class, 'myApplications']);
    Route::post('/coach/requests', [CoachManagementController::class, 'storeRequest']);
    Route::patch('/coach/requests/{requestId}/accept', [CoachManagementController::class, 'acceptRequest']);
    Route::patch('/coach/requests/{requestId}/decline', [CoachManagementController::class, 'declineRequest']);
    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::patch('/notifications/read-all', [NotificationController::class, 'markAllRead']);
    Route::patch('/notifications/{notification}/read', [NotificationController::class, 'markRead']);
    Route::delete('/notifications/{notification}', [NotificationController::class, 'destroy']);
    Route::post('/notifications/streak', [NotificationController::class, 'store']);
    Route::post('/step-submissions', [StepSubmissionController::class, 'store']);
    Route::get('/step-submissions/mine', [StepSubmissionController::class, 'mine']);
    Route::get('/coach/step-submissions', [StepSubmissionController::class, 'index']);
    Route::patch('/coach/step-submissions/{stepSubmission}/approve', [StepSubmissionController::class, 'approve']);
    Route::patch('/coach/step-submissions/{stepSubmission}/decline', [StepSubmissionController::class, 'decline']);
    Route::post('/accountability-meetings', [AccountabilityMeetingController::class, 'store']);
    Route::patch('/accountability-meetings/{accountabilityMeeting}', [AccountabilityMeetingController::class, 'update']);
    Route::delete('/accountability-meetings/{accountabilityMeeting}', [AccountabilityMeetingController::class, 'destroy']);
    Route::get('/accountability-meetings/groups', [AccountabilityMeetingController::class, 'groups']);
    Route::get('/accountability-meetings/mine', [AccountabilityMeetingController::class, 'mine']);
    Route::post('/accountability-meetings/{accountabilityMeeting}/join', [AccountabilityMeetingController::class, 'join']);
    Route::get('/coach/accountability-meetings', [AccountabilityMeetingController::class, 'index']);
});
